name: 'build-test'
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: philipssoftware/sonar-scanner:4.7.0.2747

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Build distribution
        run: yarn build

      - name: Update dist in the repository
        if: github.event_name != 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v4.15.4
        with:
          commit_message: 'chore(ci): Updating dist'
          file_pattern: dist/*
